apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
  labels:
    app: python-flask-app
spec:
  type: NodePort
  ports:
    - port: 5010
      targetPort: 5010
      nodePort: 30010
  selector:
    app: python-flask-app